SET SERVEROUTPUT ON

BEGIN EXECUTE IMMEDIATE 'DROP TABLE employees_copy'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE employees_copy (
   employee_id NUMBER PRIMARY KEY,
   first_name VARCHAR2(50),
   last_name VARCHAR2(50),
   salary NUMBER(8,2),
   commission_pct NUMBER(2,2)       
);

INSERT INTO employees_copy VALUES (100,'Steven','King', 24000, NULL);
INSERT INTO employees_copy VALUES (101,'Neena','Kochhar', 17000, NULL);
INSERT INTO employees_copy VALUES (103,'Alexander','Hunold', 9000, NULL);
INSERT INTO employees_copy VALUES (104,'Bruce','Ernst', 6000, NULL);
INSERT INTO employees_copy VALUES (145,'John','Russell', 14000, 0.40);
INSERT INTO employees_copy VALUES (146,'Karen','Partners', 13500, 0.30);
INSERT INTO employees_copy VALUES (150,'Peter','Tucker', 10000, 0.30);
INSERT INTO employees_copy VALUES (151,'David','Bernstein', 9500, 0.25);
INSERT INTO employees_copy VALUES (152,'Peter','Hall', 9000, 0.25);
INSERT INTO employees_copy VALUES (176,'Jonathon','Taylor', 8600, 0.20);
INSERT INTO employees_copy VALUES (200,'Jennifer','Whalen', 4400, NULL);
INSERT INTO employees_copy VALUES (201,'Michael','Hartstein', 13000, NULL);
INSERT INTO employees_copy VALUES (205,'Shelley','Higgins', 12000, NULL);
INSERT INTO employees_copy VALUES (206,'William','Gietz', 8300, NULL);
COMMIT;

-- Tabelul in care se scriu logurile
BEGIN EXECUTE IMMEDIATE 'DROP TABLE debug_log'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE debug_log (
   log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- autoincrement
   log_time    TIMESTAMP     DEFAULT SYSTIMESTAMP,
   module_name VARCHAR2(100), -- din ce procedura vine logul
   line_no     NUMBER, -- linia din cod
   log_level   VARCHAR2(10), -- DEBUG / INFO / WARN / ERROR
   log_message VARCHAR2(4000),
   session_id  VARCHAR2(50)  DEFAULT SYS_CONTEXT('USERENV','SESSIONID') -- id-ul sesiunii care a scris logul
);

-- Specificatia pachetului
CREATE OR REPLACE PACKAGE debug_utils IS

   g_debug_mode BOOLEAN := FALSE; -- flag global: logam doar cand e TRUE
   g_log_level  VARCHAR2(10) := 'DEBUG'; -- de la ce nivel in sus logam

   c_debug CONSTANT VARCHAR2(10) := 'DEBUG';
   c_info CONSTANT VARCHAR2(10) := 'INFO';
   c_warn CONSTANT VARCHAR2(10) := 'WARN';
   c_error CONSTANT VARCHAR2(10) := 'ERROR';

   PROCEDURE enable_debug;
   PROCEDURE disable_debug;
   PROCEDURE set_log_level(p_level IN VARCHAR2); -- schimba nivelul in timpul executiei

   PROCEDURE log(p_module_name IN VARCHAR2, p_line IN NUMBER, p_message IN VARCHAR2, p_level IN VARCHAR2 DEFAULT c_info);

   PROCEDURE log_msg(p_message IN VARCHAR2, p_module_name IN VARCHAR2 DEFAULT NULL);
   PROCEDURE log_variable(p_name IN VARCHAR2, p_value IN VARCHAR2, p_module_name IN VARCHAR2 DEFAULT NULL);
   PROCEDURE log_error(p_proc IN VARCHAR2, p_err IN VARCHAR2);

END debug_utils;
/

-- Corpul pachetului
CREATE OR REPLACE PACKAGE BODY debug_utils IS

   -- dau un numar fiecarui nivel ca sa le pot compara intre ele
   FUNCTION rang_nivel(p_level IN VARCHAR2) RETURN NUMBER IS
   BEGIN
      CASE UPPER(p_level)
         WHEN c_debug THEN RETURN 1;
         WHEN c_info  THEN RETURN 2;
         WHEN c_warn  THEN RETURN 3;
         WHEN c_error THEN RETURN 4;
         ELSE RETURN 2;
      END CASE;
   END rang_nivel;

   PROCEDURE enable_debug IS
   BEGIN
      g_debug_mode := TRUE;
   END enable_debug;

   PROCEDURE disable_debug IS
   BEGIN
      g_debug_mode := FALSE;
   END disable_debug;

   PROCEDURE set_log_level(p_level IN VARCHAR2) IS
   BEGIN
      g_log_level := UPPER(p_level);
   END set_log_level;

   PROCEDURE log(p_module_name IN VARCHAR2, p_line IN NUMBER, p_message IN VARCHAR2, p_level IN VARCHAR2 DEFAULT c_info) IS
      PRAGMA AUTONOMOUS_TRANSACTION;   -- logul ramane scris chiar daca procedura apelanta face rollback
   BEGIN

      IF NOT g_debug_mode OR rang_nivel(p_level) < rang_nivel(g_log_level) THEN -- daca debugul e oprit sau mesajul e sub nivelul setat, nu scriem nimic
         RETURN;
      END IF;

      INSERT INTO debug_log (module_name, line_no, log_level, log_message)
      VALUES (p_module_name, p_line, UPPER(p_level), p_message);

      COMMIT;
   END log;

   PROCEDURE log_msg(p_message IN VARCHAR2, p_module_name IN VARCHAR2 DEFAULT NULL) IS
   BEGIN
      log(p_module_name, NULL, p_message, c_info);
   END log_msg;

   PROCEDURE log_variable(p_name IN VARCHAR2, p_value IN VARCHAR2, p_module_name IN VARCHAR2 DEFAULT NULL) IS
   BEGIN
      log(p_module_name, NULL, p_name || ' = ' || p_value, c_debug);
   END log_variable;

   PROCEDURE log_error(p_proc IN VARCHAR2, p_err IN VARCHAR2) IS
   BEGIN
      log(p_proc, NULL, p_err, c_error);
   END log_error;

END debug_utils;
/

-- Procedura care mareste salariile
-- Cine are comision primeste procentul lui, cine nu are primeste 2%.
CREATE OR REPLACE PROCEDURE adjust_salaries_by_commission IS

   c_modul CONSTANT VARCHAR2(100) := 'ADJUST_SALARIES_BY_COMMISSION';

   CURSOR c_angajati IS
      SELECT employee_id, salary, commission_pct
      FROM   employees_copy;

   v_ang c_angajati%ROWTYPE; -- variabila de tip record, cu aceleasi campuri ca in cursor, daca schimb selectu variabila se schimba automat
   v_salariu_nou employees_copy.salary%TYPE;

BEGIN
   debug_utils.log(c_modul, $$PLSQL_LINE, 'Incep actualizarea salariilor');

   -- citire date
   OPEN c_angajati;
   debug_utils.log(c_modul, $$PLSQL_LINE, 'Am deschis cursorul cu angajatii');

   LOOP
      FETCH c_angajati INTO v_ang;
      EXIT WHEN c_angajati%NOTFOUND;

      -- calcul
      IF v_ang.commission_pct IS NOT NULL THEN
         v_salariu_nou := v_ang.salary + v_ang.salary * v_ang.commission_pct;
         debug_utils.log(c_modul, $$PLSQL_LINE, 'Angajatul ' || v_ang.employee_id || ' are comision ' || v_ang.commission_pct, debug_utils.c_debug);
      ELSE
         v_salariu_nou := v_ang.salary * 1.02;
         debug_utils.log(c_modul, $$PLSQL_LINE, 'Angajatul ' || v_ang.employee_id || ' nu are comision, primeste 2%', debug_utils.c_debug);
      END IF;

      debug_utils.log_variable('v_salariu_nou', TO_CHAR(v_salariu_nou), c_modul);

      -- actualizare
      UPDATE employees_copy
      SET    salary = v_salariu_nou
      WHERE  employee_id = v_ang.employee_id;
   END LOOP;

   debug_utils.log(c_modul, $$PLSQL_LINE, 'Am actualizat ' || c_angajati%ROWCOUNT || ' angajati');
   CLOSE c_angajati;

   COMMIT;
   debug_utils.log_msg('Gata, salariile au fost actualizate', c_modul);

EXCEPTION
   WHEN OTHERS THEN
      ROLLBACK;
      debug_utils.log_error(c_modul, SQLERRM);
      IF c_angajati%ISOPEN THEN --daca erorul s-a produs inainte de a inchide cursorul, il inchid aici
         CLOSE c_angajati;
      END IF;
      RAISE; -- aruncam din nou exceptia ca sa se vada si in afara procedurii
END adjust_salaries_by_commission;
/



-- a) cu debugul oprit, chiar daca cer o logare, nu se scrie nimic
BEGIN
   debug_utils.disable_debug;
   debug_utils.log_msg('mesaj de test, cu debugul oprit');
END;
/
SELECT COUNT(*) AS loguri_cu_debug_oprit FROM debug_log;   -- trebuie sa fie 0

-- b) pornesc debugul si rulez procedura o singura data
BEGIN
   debug_utils.enable_debug;
   debug_utils.set_log_level('DEBUG');
   adjust_salaries_by_commission;
END;
/

SELECT log_id, module_name, line_no, log_level, log_message
FROM   debug_log
ORDER  BY log_id;